# Generated by Django 5.0.6 on 2024-07-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alimentacion_delete_alimentación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimentacion',
            old_name='peso',
            new_name='tamanio',
        ),
    ]
