# Generated by Django 5.0.6 on 2024-07-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_rename_peso_alimentacion_tamanio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentacion',
            name='tamanio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collares',
            name='tamanio',
            field=models.CharField(max_length=50),
        ),
    ]
